### ISSUE TITLE
cis_1_7_2 fails to apply as fact is never empty (returns 'true' or 'false')

### ISSUE THREAD

**Issue by canihavethisone** [fervidus/secure_linux_cis#21]
line 17 needs to be changed from
`  if $enforced and !$facts['gnome_installed'].empty { `

to 
`   if $enforced and $facts['gnome_installed'] {`

so it works with the refactored fact.

I can do this in my next pull request, however if another contributor has a pull request sooner can they please incorporate the fix?

**Comment by bjvrielink** [comment]
I also noticed this (but too late). I've fixed it locally in exactly the same way.
I have a few minor updates I'd like to make, but lack the time to put it into code and test it right now, so feel free to put this into your next PR.

**Comment by canihavethisone** [comment]
I have also found that despite the new rootpw fact being confined to debian, when a windows host runs from the same puppetmaster (and gets the universal facts) it errors on the "require 'shadow'" line with 
`cannot load such file -- shadow`

This persists even if I move the require shadow within the confine space.

Any thoughts?  The redhat facts haven't presented errors on Windows hosts since the confine statements were added.

**Comment by bjvrielink** [comment]
I think the Red Hat facts not giving issues is because previously almost no facts used 'require'.

I'm a little surprised that the 'require' version of this fact made it into the released version. In my branch (https://github.com/bjvrielink/secure_linux_cis/blob/debian/lib/facter/rootpw.rb) I already did abandon it, as it was not working (Puppet's Ruby interpreter does not have the shadow gem).

Please consider adopting my "fixed" version, or remind me to do that :)

**Comment by canihavethisone** [comment]
addressed these issues in PR for v1.0.17
